<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CMS.Database\CMS.Database.csproj" />
      <ProjectReference Include="..\CMS.Helpers\CMS.Helpers.csproj" />
      <ProjectReference Include="..\CMS.Interfaces\CMS.Interfaces.csproj" />
      <ProjectReference Include="..\CMS.Models.Database\CMS.Models.Database.csproj" />
      <ProjectReference Include="..\CMS.Models.Services\CMS.Models.Services.csproj" />
    </ItemGroup>

</Project>
